version: '3'
services:
  workspace:
    image: workspace
    build:
      context: ./
      dockerfile: docker/workspace/Dockerfile
    volumes:
      - ./:/myapp
    working_dir: "/myapp"
    ports:
      - 80:80
  mysql:
    build:
      context: ./
      dockerfile: docker/mysql57/Dockerfile
    ports:
      - 3306:3306
    env_file:
      - docker/mysql57/mysql57.env